//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcDbFirstLecture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Person
    {
        public int id { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> crtBy { get; set; }
        public Nullable<System.DateTime> crtOn { get; set; }
        public Nullable<System.DateTime> modOn { get; set; }
        public Nullable<int> modBy { get; set; }
    }
}
